# Firstly we will use the download.file function to download the file and then use destfile function to give a location to the downloaded file
download.file("https://raw.githubusercontent.com/markziemann/SLE712_files/master/bioinfo_asst3_part1_files/gene_expression.tsv", destfile = "gene_expression.tsv")

# Question 1. Read in the file, making the gene accession numbers the row names. Show a table of values for the first six genes.
# We will use read.table function to convert and read the values in tabular format.
gene <- read.table("gene_expression.tsv")
head(gene) # Show a table of value for the first six genes
str(gene)

# Question 2. Make a new column which is the mean of the other columns. Show a table of values for the first six genes.
# We will use the gene$Mean function to add a columns of mean values and then rowMean function will add the mean values to the columns.
gene <- read.table("gene_expression.tsv" , header = TRUE, stringsAsFactors = FALSE, row.names = 1)
gene$Means <- rowMeans(gene)
head(gene)
str(gene)

# Question 3. List the 10 genes with highest gene expression
# We will use order function to arrange values in an ascending order and a "-" will be used to determine highest mean expression and also arranges them from higher to lower. Header is attributed with 10 in order to get only 10 values. 
order(gene$Mean)
gene[order(gene$Mean), ]
gene[order(-gene$Mean), ]
head(gene[order(-gene$Mean), ])
head(gene[order(-gene$Mean),],10)

# Question 4. Determine the number of genes with a mean <10.
# We will use <10 and ,3 with gene function in order to get 
gene[(gene[,3]<10),]
nrow(gene)

# Question 5. Make a histogram plot of the mean values in png format and paste it to your report.
hist(gene$Mean)
hist(gene$Mean, breaks= 20)

# Question 6. Import this csv file into an R object. What are the column names?
# In order to import the file in R, we will firstly use download.file command and then the dest.file command to provide a destination for the downloaded file.
download.file("https://raw.githubusercontent.com/markziemann/SLE712_files/master/bioinfo_asst3_part1_files/growth_data.csv", destfile = "growth_data.csv")
gd <- read.table("growth_data.csv")
head(gd)
str(gd)
colnames(gd)

# Question 7. Calculate the mean and standard deviation of tree circumferance at the start and end of the study at the both sides.
# We will begin solving the problem with northeast and then shift our focus to southwest.
gd<-read.csv("growth_data.csv")
subset(gd,Site=="northeast")
NE <- subset(gd,Site=="northeast")
head(NE)
tail(NE)
str(NE)
mean(NE$Circumf_2004_cm)
mean(NE$Circumf_2019_cm)
sd(NE$Circumf_2004_cm)
sd(NE$Circumf_2019_cm)

#Now we will calculate the values of mean and standard deviation for the southwest.
gd<-read.csv("growth-data.csv")
subset(gd,Site=="southwest")
SW <- subset(gd,Site=="southwest")
head(SW)
tail(SW)
str(SW)
mean(SW$Circumf_2004_cm)
mean(SW$Circumf_2019_cm)
sd(SW$Circumf_2004_cm)
sd(SW$Circumf_2019_cm)

# Question 8. Make a box plot of tree circumference at the start and end of the study at both sites.
boxplot(NE$Circumf_2004_cm, NE$Circumf_2019_cm)
boxplot(NE$Circumf_2004_cm, NE$Circumf_2019_cm, SW$Circumf_2004_cm, SW$Circumf_2019_cm)
boxplot(NE$Circumf_2004_cm, NE$Circumf_2019_cm, SW$Circumf_2004_cm, SW$Circumf_2019_cm, names = c("NE2004", "NE2019", "SW2004", "SW2019"), ylab="Circumfrence (cm)")
boxplot(NE$Circumf_2004_cm, NE$Circumf_2019_cm, SW$Circumf_2004_cm, SW$Circumf_2019_cm, names = c("NE2004", "NE2019", "SW2004", "SW2019"), ylab="Circumfrence (cm)", main="Growth at two plantation sites")

# Question 9. Calculate the mean growth over the past 10 years at each site.
NE$growth <-NE$Circumf_2019_cm-NE$Circumf_2009_cm
head(NE)
mean(tail(NE$growth,n=10))

SW$growth <-SW$Circumf_2019_cm-SW$Circumf_2009_cm
head(SW)
mean(tail(SE$growth,n=10))

# Question 10.Use the t.test and wilcox.test functions to estimate the p-value that the 10 year growth is different at the two sites.
t.test(SW$growth,NE$growth)
wilcox.test(SW$growth,NE$growth)

# Part 2: Determine the limits of BLAST
# We need some packages to be able to work with R. So, first we will load them.

